// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8U6gVAldOcC4N5jn_gtn9Pc-n3ZlIeMc',
    appId: '1:108683914119:web:59e033dfbaf2cc42954122',
    messagingSenderId: '108683914119',
    projectId: 'tmdb-flutter-2be66',
    authDomain: 'tmdb-flutter-2be66.firebaseapp.com',
    storageBucket: 'tmdb-flutter-2be66.appspot.com',
    measurementId: 'G-LRWYX3NJCW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfwyUEdGlIociaLmlUwUOre2AJ3X20U44',
    appId: '1:108683914119:android:099d35698c0d9a38954122',
    messagingSenderId: '108683914119',
    projectId: 'tmdb-flutter-2be66',
    storageBucket: 'tmdb-flutter-2be66.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEQHeUlAuU8OqdAEWX4WblP0lCH9zvQ1o',
    appId: '1:108683914119:ios:e2850cd86fe2e789954122',
    messagingSenderId: '108683914119',
    projectId: 'tmdb-flutter-2be66',
    storageBucket: 'tmdb-flutter-2be66.appspot.com',
    iosBundleId: 'flutter.tmdb.tmdbFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEQHeUlAuU8OqdAEWX4WblP0lCH9zvQ1o',
    appId: '1:108683914119:ios:59b22a73c559edbb954122',
    messagingSenderId: '108683914119',
    projectId: 'tmdb-flutter-2be66',
    storageBucket: 'tmdb-flutter-2be66.appspot.com',
    iosBundleId: 'flutter.tmdb.tmdbFlutter.RunnerTests',
  );
}
